name: build

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always
  CARGO_INCREMENTAL: 0

jobs:
  build-node:
    name: build-node
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '12'

      - name: Display Node versions
        run: |
          node --version
          npm --version

      - name: Install dependencies
        run: npm install

      - name: Cache examples
        uses: actions/cache@v3
        with:
          path: examples
          key: ${{ hashFiles('script/parse-examples') }}

      - name: Test corpus & parse examples
        run: npm test

  build-rust:
    name: build-rust
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal

      - name: Build
        run: cargo build --release

      - name: Test
        run: cargo test

  build-swift:
    name: build-swift
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build
        run: swift build

      - name: Test
        run: swift test
